//
//  SUDRuntime2GameUserManager.h
//  SUD_GIP
//
//  Created by kaniel on 1/14/26.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN
/**
 * User and Game Identity Constants
 */
/// The unique identifier (ID) for the user.
extern NSString * const SUD_RT2_KEY_USER_ID;
/// The unique identifier (ID) for the game.
extern NSString * const SUD_RT2_KEY_USER_GAME_ID;

/**
 * Game Metadata and Statistics Constants
 */
/// Reserved field for internal game-specific data.
extern NSString * const SUD_RT2_KEY_USER_GAME_RESERVE;
/// Custom additional information or metadata for the game.
extern NSString * const SUD_RT2_KEY_USER_GAME_EXTRA_INFO;
/// The client-side timestamp of the last time the game was launched.
extern NSString * const SUD_RT2_KEY_USER_GAME_LAST_PLAY_TIME;
/// The total number of successful game sessions/runs.
extern NSString * const SUD_RT2_KEY_USER_GAME_PLAYED;
/// Boolean flag indicating whether the game has been marked as deleted by the user.
extern NSString * const SUD_RT2_KEY_USER_GAME_REMOVED;

/**
 * File System and Storage Path Constants
 */
/// The root directory for persistent files saved via FileSystemManager.
extern NSString * const SUD_RT2_KEY_USER_GAME_DATA_PATH;
/// The root directory for temporary files generated by functional APIs.
extern NSString * const SUD_RT2_KEY_USER_GAME_TEMP_PATH;
/// The file path to the database used by the LocalStorage API.
extern NSString * const SUD_RT2_KEY_USER_GAME_LOCAL_STORAGE_PATH;

/**
 * Permission Type Constants
 */
/// Permission key for audio recording (Microphone).
extern NSString * const SUD_RT2_KEY_PERMISSION_RECORD;
/// Permission key for camera access.
extern NSString * const SUD_RT2_KEY_PERMISSION_CAMERA;
/// Permission key for geographic location access.
extern NSString * const SUD_RT2_KEY_PERMISSION_LOCATION;
/// Permission key for saving media to the photo album/gallery.
extern NSString * const SUD_RT2_KEY_PERMISSION_SAVE_TO_ALBUM;


/**
 * @protocol SUDRuntime2GameUserManager
 * @brief Manages user-specific game data, storage paths, and metadata synchronization.
 */
@protocol SUDRuntime2GameUserManager <NSObject>

/**
 * Cancels any pending asynchronous requests to remove game data.
 */
- (void)cancelRemoveGameRequest;

/**
 * Retrieves the local file system paths (Data, Temp, LocalStorage) for a specific user and game.
 * @param userId The unique ID of the user.
 * @param gameId The unique ID of the game.
 * @return A dictionary containing the path constants, or nil if not initialized.
 */
- (nullable NSDictionary *)getGameDataPaths:(nonnull NSString *)userId
                                     gameId:(nonnull NSString *)gameId;

/**
 * Retrieves the metadata and statistics for a specific game associated with a user.
 * @param userId The unique ID of the user.
 * @param gameId The unique ID of the game.
 * @return A dictionary containing game info (Last Play Time, Played Count, etc.), or nil.
 */
- (nullable NSDictionary *)getGameInfo:(NSString *)userId
                                gameId:(NSString *)gameId;

/**
 * Retrieves a list of all games that have stored information on the current device.
 * @return An array of dictionaries, each containing game information.
 */
- (nullable NSArray<NSDictionary *> *)listGameInfo;

/**
 * Performs a complete removal of game assets and data for a user. Usually involves network requests.
 * @param userId The unique ID of the user.
 * @param gameId The unique ID of the game.
 * @param completion Callback invoked when the removal process completes.
 */
- (void)removeGame:(nonnull NSString *)userId
            gameId:(nonnull NSString *)gameId
        completion:(nullable void (^)(NSError * _Nullable error))completion;

/**
 * Deletes the local metadata/record for a game without necessarily deleting physical assets.
 * @param userId The unique ID of the user.
 * @param gameId The unique ID of the game.
 * @return YES if the record was successfully removed, NO otherwise.
 */
- (BOOL)removeGameInfo:(nonnull NSString *)userId
                gameId:(nonnull NSString *)gameId;

/**
 * Updates the metadata or configuration for a specific game and user.
 * @param userId The unique ID of the user.
 * @param gameId The unique ID of the game.
 * @param info A dictionary containing the new info to be saved.
 * @return YES if the data was successfully saved, NO otherwise.
 */
- (BOOL)setGameInfo:(nonnull NSString *)userId
             gameId:(nonnull NSString *)gameId
               info:(nonnull NSDictionary *)info;

@end
NS_ASSUME_NONNULL_END
