platform :ios, '11.0'
use_frameworks!

target 'QuickStart' do
  pod 'Masonry'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod "MJExtension"
  pod 'AFNetworking'
  # 图片加载
  pod 'SDWebImage', '5.12.2'
  #pod 'SUDGI', :path => '../../'
  pod 'SUDGI', '2.0.0'
  pod 'SUDOPWrappedClientKit', :path => '../../SUDOPWrappedClientKit/'
end

post_install do |installer|
    # disable ENABLE_BITCODE
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
    # 修复新版 Xcode SDK 中 netinet6/in6.h 私有头文件问题
    Dir.glob('Pods/**/*.{m,mm}').each do |file|
      content = File.read(file)
      if content.include?("#import <netinet6/in6.h>")
        content.gsub!("#import <netinet6/in6.h>\n", '')
        File.chmod(0644, file)
        File.write(file, content)
        puts "✅ 已修复 #{file} 的 netinet6/in6.h 问题"
      end
    end
end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      FileUtils.chmod("+w", name) #add
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
